name: Check Label

on:
  pull_request:
    branches:
      - 'main'

jobs:
  publishBeta:
    runs-on: ubuntu-latest
    name: Check label
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Check Label
        uses: checkdigit/github-actions/check-label@check-label-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: '*'
