name: Check Published

on:
  workflow_dispatch:
  schedule:
    - cron: '37 08 * * 1'
  pull_request:
    branches:
      - 'main'

jobs:
  checkPublished:
    runs-on: ubuntu-latest
    name: Check Published
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Check Published
        uses: checkdigit/github-actions/check-published@check-published
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          DEBUG: '*'
