name: Check Label

on:
  pull_request:
    branches:
      - 'main'

jobs:
  publishBeta:
    runs-on: ubuntu-latest
    name: Check label
    strategy:
      matrix:
        node-version: ['20.x', '21.x']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Check Label
        uses: checkdigit/github-actions/check-label@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
