name: Check Label

on:
  pull_request:
    branches:
      - 'main'
jobs:
  publishBeta:
    runs-on: ubuntu-latest
    name: Check label
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Check Label
        uses: checkdigit/github-actions/check-label@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Failed
        if: always()
        uses: checkdigit/github-actions/check-failed-actions@check-failed-actions
        with:
          status: ${{ job.status }}
        env:
          SLACK_FAILED_URL: ${{ secrets.SLACK_PUBLISH_MISMATCH }}
          DEBUG: '*'

#  checkJob:
#    runs-on: ubuntu-latest
#    name: check failed actions
#    if: always()
#    needs: publishBeta
#    steps:
