name: Coverage

on:
  pull_request:
    branches:
      - 'main'

env:
  CI: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Calculate Code Coverage
        run: npm run ci:coverage
      - name: Create Coverage Report for base branch
        run: |
          mv coverage/lcov.info coverage/lcov_head.info
          git fetch
          git checkout origin/${{ github.event.pull_request.base.ref }}
          npm ci --ignore-scripts && npm run ci:coverage
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Post Coverage Report
        uses: checkdigit/github-actions/coverage-reporter@main
        with:
          lcov-file: 'coverage/lcov_head.info'
          lcov-base: 'coverage/lcov.info'
          delete-old-comments: true
