name: Publish Beta Package

on:
  pull_request:
    branches:
      - 'main'

jobs:
  comment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Audit Signatures
        run: npm audit signatures
      - name: Run Test
        run: npm run ci:test
      - name: Prepare Beta
        uses: checkdigit/github-actions/prepare-beta@prepare-beta
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
